server:
  port: 9099

spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
    max-file-size: 200MB
    max-request-size: 200MB
  jackson:
    serialization:
      write-null-map-values: true

#showSql
logging:
  level:
    com:
      example:
        mapper: debug